### ISSUE TITLE
feature: remove husky

### ISSUE THREAD

**Issue by zhaoyao91** [weiran-zsd/dts-cli#101]
### Current Behavior

when init project with dts-cli, it installs husky, which breaks the hooks of git when in monorepo.

### Desired Behavior

no husky installed, or there is options in the cli

### Suggested Solution

add a question to decide if husky needed.

**Comment by aladdin-add** [comment]
a cli option like `--no-husky` sounds good to me! 👍 
PRs are welcome!

**Comment by zhaoyao91** [comment]
@aladdin-add should we use cli options or questions? the whole `create` cmd is driven by questions by now.

**Comment by aladdin-add** [comment]
it does support cli options, e.g. `dts create mylib --template=basic` (but not documented). so, we just need a new option to opt-out husky.
