### ISSUE TITLE
noClean option for build

### ISSUE THREAD

**Issue by dastein1** [weiran-zsd/dts-cli#103]
### Current Behavior

The watch command features a _noClean_ option which does not clean the build folder. The build command does not.

### Desired Behavior

We'd like to run multiple build commands (for multiple entries until #55 is supported) and would like to retain the _dist_ folder between those.

### Suggested Solution

Add the same _noClean_ option to the build command too.

### Who does this impact? Who is this for?

Some advanced usages / edge cases.

### Describe alternatives you've considered

Named exports from a barrel file.

### Additional context

-

**Comment by aladdin-add** [comment]
makes sense! 👍

**Comment by aladdin-add** [comment]
released in [v0.20.0](https://github.com/weiran-zsd/dts-cli/releases/tag/v0.20.0) 🎉
