### ISSUE TITLE
Rollup type definitions

### ISSUE THREAD

**Issue by igordanchenko** [weiran-zsd/dts-cli#108]
### Current Behavior

TypeScript compiler outputs all type definitions into the `dist` folder regardless of whether they are relevant to the components exported from the library. Even dead code that doesn't make its way into the final .js rollup still produces type definitions in the `dist` folder. Unless you take some extra steps, all those .d.ts files end up in your npm package.

Let's assume the following project structure:
```
src
  foo
    foo.tsx
  bar
    bar.tsx
  ComponentA.tsx
  ComponentB.tsx
  index.tsx
```

`dts-cli build` produces the following `dist` output:
```
dist
  foo
    foo.d.ts
  bar
    bar.d.ts
  ComponentA.d.ts
  ComponentB.d.ts
  foo-bar.cjs.development.js
  foo-bar.cjs.production.min.js
  foo-bar.esm.js
  index.d.ts
  index.js
```

### Desired Behavior

1) Produce only one .d.ts file - `index.d.ts`
2) Tree-shake all unused type definitions.

so that the final output looks like the one below:

```
dist
  foo-bar.cjs.development.js
  foo-bar.cjs.production.min.js
  foo-bar.esm.js
  index.d.ts
  index.js
```

### Suggested Solution

I achieved the desired goal with [rollup-plugin-dts](https://github.com/Swatinem/rollup-plugin-dts), but I didn't find an elegant way to plug into the build pipeline to execute a separate rollup build after all rollups are done. I ended up with the following patch package:

```diff
diff --git a/node_modules/dts-cli/dist/index.js b/node_modules/dts-cli/dist/index.js
index d5d2644..6285cd8 100755
--- a/node_modules/dts-cli/dist/index.js
+++ b/node_modules/dts-cli/dist/index.js
@@ -34,6 +34,8 @@ const utils_2 = require("./templates/utils");
 const deprecated = (0, tslib_1.__importStar)(require("./deprecated"));
 const sort_package_json_1 = (0, tslib_1.__importDefault)(require("sort-package-json"));
 const pkg = require('../package.json');
+const dts = require('rollup-plugin-dts').default;
+const del = require('rollup-plugin-delete');
 const prog = (0, sade_1.default)('dts');
 let appPackageJson;
 try {
@@ -60,6 +62,18 @@ async function jsOrTs(filename) {
                 : '.js';
     return (0, utils_1.resolveApp)(`${filename}${extension}`);
 }
+const rollupTypesConfig = {
+        input: "dist/types/index.d.ts",
+        output: { file: "dist/index.d.ts", format: "es" },
+        plugins: [
+            dts(),
+            del({ hook: "buildEnd", targets: "dist/types" })
+        ]
+    };
+async function rollupTypes() {
+    const bundle = await (0, rollup_1.rollup)(rollupTypesConfig);
+    await bundle.write(rollupTypesConfig.output);
+}
 async function getInputs(entries, source) {
     return (0, jpjs_1.concatAllArray)([]
         .concat(entries && entries.length
@@ -261,6 +275,7 @@ prog
 `);
             try {
                 await deprecated.moveTypes();
+                await rollupTypes();
                 if (firstTime && opts.onFirstSuccess) {
                     firstTime = false;
                     run(opts.onFirstSuccess);
@@ -314,6 +329,9 @@ prog
         })
             .then(async () => {
             await deprecated.moveTypes();
+        })
+            .then(async () => {
+            await rollupTypes();
         });
         logger(promise, 'Building modules');
         await promise;
```

I'm curious if there is a more straightforward approach that I simply overlooked. If not, would you be interested in adding this as a feature to `dts-cli` behind a feature flag? I'll be happy to contribute a more generic solution.

### Who does this impact? Who is this for?

I'm assuming this can be useful for most developers working on TypeScript libraries that roll up all their code into a single file without preserving the directory structure.

### Describe alternatives you've considered

There are some alternative options (i.e. `api-extractor`) that I haven't explored closely since `rollup-plugin-dts` option appears to fit more naturally into `dts-api` pipeline.

**Comment by aladdin-add** [comment]
interesting idea! 👍 

it seems a good enhancement - I don't think it needs to be behind a flag. PRs are welcome! 😄

**Comment by igordanchenko** [comment]
I meant command line option so that this feature could be an opt-in. Or do you think it's okay to enable it by default?

**Comment by aladdin-add** [comment]
yes, I'm not see why devs don't want it. And, we can add an option to opt-out (if someone asks).

**Comment by aladdin-add** [comment]
yes, I'm not see why devs don't want it. And, we can add an option to opt-out (if someone asks).

**Comment by igordanchenko** [comment]
PR is ready. 

Types rollup won't run if any of the following is true:
 - tsconfig.json `compilerOptions.declaration` is explicitly set to `false`
 - tsconfig.json `compilerOptions.declarationDir` is not defined or pointing to a folder outside of `dist`

Added `"declarationDir": "dist/types"` to `dts-cli create` templates so types rollup will be enabled by default for new projects. Existing projects will need to add `declarationDir` to their tsconfig.json manually. Please let me know if you think it will be better to enable this feature for all existing projects automatically, and I'll make the corresponding change.

**Comment by aladdin-add** [comment]
a big thanks! :)

is the config in `tsconfig.json` really needed? what do you think reading `pkg.typings`?

an example: `{"typings": "dist/index.d.ts"}`, it can be enabled even if not configured in `tsconfig.json`.

**Comment by igordanchenko** [comment]
> is the config in tsconfig.json really needed?

No, not really. It was a way of making this feature an opt-in for existing projects. But if you approve enabling this feature for existing projects (see my previous comment), then `tsconfig.json` change will not be needed at all. And I'm assuming it should be handled via breaking change release?

**Comment by aladdin-add** [comment]
I would like it to be the default. the on/off config is just `pkg.typings`.

not sure it should be a breaking change; it seems does not break anything. a minor release also makes sense?

**Comment by igordanchenko** [comment]
PR is updated.

Types rollup won't run if any of the following is true:
 - there are no `typings` or `types` entries in package.json 
 - tsconfig.json `compilerOptions.declaration` is explicitly set to false
 - tsconfig.json `compilerOptions.declarationDir` is pointing to a folder outside of `dist`

Works with both custom `compilerOptions.declarationDir` or none at all (`dist/types` is used as compilation output and is deleted when rollup is done)
