### ISSUE TITLE
v2 changes

### ISSUE THREAD

**Issue by aladdin-add** [weiran-zsd/dts-cli#121]
it won't happen soon, just want to list all the possible things:
* Node.js
  * Drop Node 12 support (end-of-life 2022-04-30)
  * Drop Node 13 support (end-of-life 2020-06-01)
  * Drop Node 14 support (end-of-life 2023-04-30)
  * Drop Node 15 support (end-of-life 2021-06-01)
  * Drop Node 17 support (end-of-life 2022-06-01)
* jest v28 https://jestjs.io/blog/2022/04/25/jest-28, https://jestjs.io/docs/upgrading-to-jest29
* Typescript v5.0 https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/
* rollup v3: https://www.rollupjs.com/guide/migration
* upgrade react/react-dom to v18 (template)
* Convert to esm? (ts v4.7)
* ...

**Comment by ToppleTheNun** [comment]
Maybe consider switching dts.config.ts/dts.config.js to use a `defineConfig` function similar to how vitest does?

Example:
```typescript
import { defineConfig } from 'dts-cli/config';

export default defineConfig({
  rollup: (config: RollupOptions, options: DtsOptions) => // ...
});
```

**Comment by aladdin-add** [comment]
For better compat, I was thinking to support both, and it can be in a minor release - as no longer a breaking change?

**Comment by mrmartineau** [comment]
How about using [Vitest](https://vitest.dev/) instead of Jest? The API is almost the same and the performance is so much better.

**Comment by aladdin-add** [comment]
sounds interesting! :🤔

* rollup => vite (lib mode)
* jest => vitest

**Comment by heath-freenome** [comment]
They are already on Jest 29!?

**Comment by heath-freenome** [comment]
Consider Node 18 as well since it goes active in November 2022

**Comment by aladdin-add** [comment]
pushed a pre-release: https://github.com/weiran-zsd/dts-cli/releases/tag/v2.0.0-beta.0

I will test it in some of my private projects and push a stable release (if works fine! 😄 ).

**Comment by aladdin-add** [comment]
v2.0 has been released: https://github.com/weiran-zsd/dts-cli/releases/tag/v2.0.0
