### ISSUE TITLE
declaration files missing

### ISSUE THREAD

**Issue by JBaczuk** [weiran-zsd/dts-cli#123]
### Current Behavior

no typescript declaration files (.d.ts) are output in the build

### Expected behavior

declaration files should be included in build output

### Suggested solution(s)

Not sure what the problem is

### Additional context

I have a tsdx component library and I swapped it out with dts-cli but the build is missing declaration files. I didn't change anything except the scripts, package.json, and renamed `tsdx.config.json` to `dts.config.json`

### Your environment

```text
  System:
    OS: macOS 11.6
    CPU: (8) x64 Apple M1
    Memory: 26.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/n/bin/node
    Yarn: 1.22.17 - ~/n/bin/yarn
    npm: 8.1.2 - ~/n/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 95.0.2
    Safari: 15.0
  npmPackages:
    typescript: ^4.5.4 => 4.5.4 
  npmGlobalPackages:
    typescript: 4.3.5
```

**Comment by igordanchenko** [comment]
Does your package.json include `types` or `typings` entry?
Can you also post your `tsconfig.json` and `dist` directory listing after the build?

**Comment by igordanchenko** [comment]
@aladdin-add this appears to be a regression from #117. I'll get a PR out shortly.
