### ISSUE TITLE
CRA test in the subfolder is executed while running `npm run test`

### ISSUE THREAD

**Issue by aboveyunhai** [weiran-zsd/dts-cli#127]
I'm not sure it's a bug or miscofig.

### Current Behavior

`npm run test` will run all the tests in the test folder as expect.
In the following cases, the sub folder test from other folder will be executed, and of cuz `failed` due to the environment setup differences.

steps to create the issues:
```
npx dts-cli create mylib
```
Go into the `mylib`, run CRA command to create a sub folder `my-app`, which will includes the default testing suites and a test case.
```
npx create-react-app my-app --template typescript
```
then run in root folder
```
npm run test
```
the test in `test` folder by dts-cli will pass but the test inside the `my-app` will run also and failed.

### Expected behavior

Those tests should be ignored?

**Comment by aladdin-add** [comment]
the default config:
https://github.com/weiran-zsd/dts-cli/blob/e6252142a46dd735150ff0972bb808bbf238aeb3/src/createJestConfig.ts#L17
so it's expected; you'll need to add your own jest config if you want to ignore `my-app`.

**Comment by aboveyunhai** [comment]
@aladdin-add  thx for the direction, the below "default" configs is what I'm looking for.
```
  "jest": {
    "testEnvironment": "jsdom",
    "testMatch": ["<rootDir>/test/*.(spec|test).{ts,tsx,js,jsx}"]
  }
```
