### ISSUE TITLE
Support for react-jsx compiler

### ISSUE THREAD

**Issue by CesarBMartinez** [weiran-zsd/dts-cli#131]
### Current Behavior

If I remove the import of React, build fails with message:
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.

### Expected behavior

the import of React it's not necessary.

**Comment by aladdin-add** [comment]
have you tried: 
```js
  "compilerOptions": {
    "jsx": "react-jsx"
  },
```

**Comment by CesarBMartinez** [comment]
@aladdin-add yes, that's the default options,
dts-cli extends "extends": "@tsconfig/create-react-app/tsconfig.json",

"extends": "@tsconfig/create-react-app/tsconfig.json",

{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Create React App",


  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "target": "es5",

    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "moduleResolution": "node",
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true
  }
}

**Comment by aladdin-add** [comment]
Ugh, it seems to work when you put it in your own tsconfig. I'm guessing there is something wrong in the `rollup-plugin-typescript2`.

**Comment by CesarBMartinez** [comment]
@aladdin-add using the "react-jsx" option in my own tsconfig worked, thanks!
