### ISSUE TITLE
How can I add some code to run before the require statement in cli.js ?

### ISSUE THREAD

**Issue by omar-dulaimi** [weiran-zsd/dts-cli#156]
### Current Behavior

I'm trying to run some code at the top of a file, before anything else runs, before imports even. But the problem is that the generated files always hoist imports up, which causes a problem for me.

What I want to do, is check if a dependency exist before trying to import it, so that I can let the user install first it.

### Expected behavior

Imports shouldn't be hoisted based on my little knowledge.

### Suggested solution(s)

There should be a way to inject some code in the cli index before the require statement.

### Your environment

```text
  System:
    OS: Linux 5.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-4310M CPU @ 2.70GHz
    Memory: 1.06 GB / 11.60 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Chrome: 101.0.4951.41
    Firefox: 99.0
  npmPackages:
    dts-cli: ^1.1.5 => 1.5.1 
    typescript: ^4.5.4 => 4.6.4 
```

**Comment by aladdin-add** [comment]
there may be some rollup plugins that can do this, but the easiest way I can see is to use a "import" on the top of the file. e.g.

```
import "./core.js";

//....
```

**Comment by omar-dulaimi** [comment]
That does not work @aladdin-add 

I added this to the top of the file:
```ts
import { version } from '../package.json'
import { check } from './zod'
check()
```

and this was generated:

```ts
'use strict';

var generatorHelper = require('@prisma/generator-helper');
var typescript = require('typescript');
var zod = require('zod');
var path = require('path');
var tsMorph = require('ts-morph');
var parenthesis = require('parenthesis');

function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }

var path__default = /*#__PURE__*/_interopDefaultLegacy(path);

var version = "0.5.4";

const check = () => {
  try {
    const zod = require('zod');

    console.log('🚀 ~ file: zod.ts ~ line 5 ~ zod', zod);
  } catch (error) {
    console.log('🚀 ~ file: zod.ts ~ line 6 ~ error', error);
    process.exit(1);
  }
};
```

you see how the imports are still in the top?

By the way, I do not see a file called cli.ts, only cli.js
so how can I really edit it if it's not exposed to be by dts-cli?

**Comment by omar-dulaimi** [comment]
Okay, so there was a `cli.js` file, and I just edited it, and it works now.

Thanks man!
