### ISSUE TITLE
Error when trying to use useState

### ISSUE THREAD

**Issue by AGSS18** [weiran-zsd/dts-cli#163]
### Current Behavior

Without making any changes besides adding a useState to the component `<Thing />` in the src file I'm getting this error:
`TypeError: Cannot read properties of null (reading 'useState')`

I'm not getting any errors in the DTS app console or my app console, it is compiling without errors or warnings. The error is showing when the component tries to mount. If I remove the useState my app is working fine.

This is how the code of the component looks like:

<img width="504" alt="Screen Shot 2022-07-06 at 18 33 26" src="https://user-images.githubusercontent.com/24236372/177659853-948a46ba-5d72-45f1-8824-52efdfcb3d68.png">

And this is the error I'm getting:

<img width="982" alt="Screen Shot 2022-07-06 at 18 31 29" src="https://user-images.githubusercontent.com/24236372/177659694-0280f437-6ecd-49b0-bf33-3e4cbdef5ca2.png">

### Your environment

```text

```

**Comment by AGSS18** [comment]
Seems like it's happening with every react hook even though I'm using the react template.

**Comment by aladdin-add** [comment]
I was not able to repro. what's your react/react-dom version? maybe using a version that does not support hooks?

**Comment by AGSS18** [comment]
I'm using 18.2.0

**Comment by aladdin-add** [comment]
emm....can you make a repro?

**Comment by aladdin-add** [comment]
ah. I got it! the cause is `npm link`. as said in the react docs:

> This problem can also come up when you use npm link or an equivalent. In that case, your bundler might “see” two Reacts — one in application folder and one in your library folder. Assuming myapp and mylib are sibling folders, one possible fix is to run npm link ../myapp/node_modules/react from mylib. This should make the library use the application’s React copy.

**Comment by aladdin-add** [comment]
https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

**Comment by AGSS18** [comment]
Thanks @aladdin-add  that really helped 🙌🏻
