### ISSUE TITLE
Consider upgrading to Jest 29 and Eslint 8

### ISSUE THREAD

**Issue by heath-freenome** [weiran-zsd/dts-cli#165]
### Current Behavior

Jest is on v27 and eslint is on v7

### Desired Behavior

Jest and Eslint have bump major versions to v29 and v8 respectively

### Suggested Solution

Updated `package.json` with the new versions... note Jest 29 requires you to import a new library

### Who does this impact? Who is this for?

All users who want the latest technologies

### Describe alternatives you've considered

Switching to a new bundler

**Comment by aladdin-add** [comment]
it will be a part of v2. related: https://github.com/weiran-zsd/dts-cli/issues/121

**Comment by aladdin-add** [comment]
closing as v2.0.0 has been released. :)
