### ISSUE TITLE
 --transpileOnly argument doesn't work

### ISSUE THREAD

**Issue by 0NotApplicable0** [weiran-zsd/dts-cli#170]
### Current Behavior

Providing  --transpileOnly argument to dts build ```dts build  --transpileOnly``` fails to build citing typescript errors.
![Screenshot 2022-08-15 103303](https://user-images.githubusercontent.com/32582432/184655640-9a16bc41-20ce-4866-b3a0-d3edab1cd7c8.png)

### Expected behavior

The same behavior as ```tsdx build --transpileOnly``` and no typescript errors are shown.

### Suggested solution(s)

Unknown at this time.

### Additional context

None.

### Your environment

```text
  System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
    Memory: 7.82 GB / 63.89 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    dts-cli: ^1.6.0 => 1.6.0
    typescript: 4.0.5 => 4.0.5
```

**Comment by 0NotApplicable0** [comment]
So after solving a few of these type errors I can only transpile even though there are several more. Not sure whats going on here.

**Comment by aladdin-add** [comment]
yes, I didn't remove any features. so if tsdx has supported, dts should be.

**Comment by 0NotApplicable0** [comment]
Seems like it was a strange one off issue. Thanks!
