### ISSUE TITLE
try to create private custom library with dts storybook but building error occurred

### ISSUE THREAD

**Issue by faizerturk** [weiran-zsd/dts-cli#173]
So I try to create a custom private library by using dts storybook template with yarn 3, what I do is creating dts storybook template and I use that repo only for storybook. Further more I push it that repo to git as private and I call that repo in my main projects as dependency like : 
"project-name": "git+ssh://......" , 
When I do yarn install , the project comes into external libraries :
<img width="256" alt="Screen Shot 2022-09-01 at 11 02 06" src="https://user-images.githubusercontent.com/86715389/187863730-81788b27-8bcf-466b-8b6e-fbb93f18a103.png">
but when I call one of story in this way I have an error like : 

Module not found: Error: Can't resolve 'further-react-common' in '/Users/macbookpro/Projects/further-storybook-ts/src'
and 
TS2307: Cannot find module 'further-react-common' or its corresponding type declarations.
<img width="913" alt="Screen Shot 2022-09-01 at 11 02 43" src="https://user-images.githubusercontent.com/86715389/187863916-e0e8492a-7167-44b9-a5a3-7f2eb65e363a.png">
<img width="843" alt="Screen Shot 2022-09-01 at 11 03 40" src="https://user-images.githubusercontent.com/86715389/187864037-8a0e97e8-1404-4ac7-9e93-75d2283d2968.png">
<img width="750" alt="Screen Shot 2022-09-01 at 11 03 36" src="https://user-images.githubusercontent.com/86715389/187864031-748dfc58-3755-40c7-b4f7-623459b92214.png">

I think it's a building error, when I install the dts-storybook projects into my main project it comes without building

**Comment by aladdin-add** [comment]
seems your `further-react-common`'s build result was not found, as you were using `"project-name": "git+ssh://......" ,`.

you can:

1. just simply run build & publish to npmjs.
2. or unignore the '/dist' files, and git push.
