### ISSUE TITLE
Running example folder with 2.0.0 fresh lib produce [vite] Internal server error: failed to resolve "extends":"@tsconfig/create-react-app/tsconfig.json" in example/tsconfig.json

### ISSUE THREAD

**Issue by leobastiani** [weiran-zsd/dts-cli#194]
# To reproduce

```
npx dts-cli create mylib --template react
cd mylib
yarn build
cd example
yarn
yarn start
```

```
yarn run v1.22.19
$ vite
▲ [WARNING] Cannot find base config file "@tsconfig/create-react-app/tsconfig.json" [tsconfig.json]

    tsconfig.json:2:13:
      2 │   "extends": "@tsconfig/create-react-app/tsconfig.json"
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  VITE v4.2.1  ready in 642 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
11:28:11 AM [vite] Internal server error: failed to resolve "extends":"@tsconfig/create-react-app/tsconfig.json" mylib/example/tsconfig.json
```

Could it be possible update example folder and use typescript 5 on it?

Thank you ❤️

**Comment by aladdin-add** [comment]
Thanks for letting me know. to fix it, you can just replace it with `@tsconfig/vite-react/tsconfig.json`.

I'll push a fix soon.

**Comment by leobastiani** [comment]
thank you ❤️
what do you think of adding a pipe line to test example folder?

**Comment by aladdin-add** [comment]
sure, that's' exactly what I'm thinking. Would you like to make a PR?

**Comment by leobastiani** [comment]
sure, I'll manage to do
I also think it should be nice setting fixed versions of all packages in
usage and updating then everyday automatically if no errors were found
what do you think?

could you make this quick fix and then I could help with others more
elaborated?

Em dom, 16 de abr de 2023 23:49, 唯然 ***@***.***> escreveu:

**Comment by aladdin-add** [comment]
> I also think it should be nice setting fixed versions of all packages in
> usage and updating then everyday automatically if no errors were found
> what do you think?

sounds good to me! 👍
