### ISSUE TITLE
Version 2.0 breaking change should mention Typescript 5 not 4

### ISSUE THREAD

**Issue by heath-freenome** [weiran-zsd/dts-cli#195]
### Current Behavior

In the 2.0 breaking changes list it says upgraded to Typescript 4 (or at least it used to, now that seems missing)

### Expected behavior

In reality 2.0 uses Typescript 5

### Suggested solution(s)

Update the `CHANGELOG.md` to describe Typescript 5.0 in the breaking changes

### Additional context

Some projects (such as mine) still have problems with using Typescript 5, thus preventing me from upgrading.  I wouldn't have attempted to use the 2.0 version had I known from reading the `CHANGELOG.md`

### Your environment

```text

```

**Comment by aladdin-add** [comment]
ops, yes, it should be mentioned, will update soon.

**Comment by aladdin-add** [comment]
updated https://github.com/weiran-zsd/dts-cli/releases/tag/v2.0.0.
