### ISSUE TITLE
Only first entry works when more than one is provided

### ISSUE THREAD

**Issue by prdxs** [weiran-zsd/dts-cli#55]
### Current Behavior

When running
`dts build -i src/components/core/Badge/index.ts -i src/components/core/CssBaseline/index.ts`
the second entry is ignored.

The `dist/` folder only contains the bundle containing the Badge component in this case.

### Expected behavior

I would expect having bundle files for CssBaseline too.

### Suggested solution(s)

I don't have a clue 😂

### Additional context

I just want to have one file for each component of a library of React components

### Your environment

```text
  System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-7560U CPU @ 2.40GHz
    Memory: 3.67 GB / 15.37 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.5/bin/yarn
    npm: 7.21.0 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Browsers:
    Brave Browser: 93.1.29.81
    Chrome: 93.0.4577.82
    Firefox: 92.0
  npmPackages:
    dts-cli: ^0.17.1 => 0.17.1 
    typescript: ^4.4.3 => 4.4.3 
```

**Comment by aladdin-add** [comment]
this is working as expected.

you can add another entry to import all components:

```js
export { default as Badge} from 'src/components/core/Badge/index.ts';
export { default as CssBaseline} from 'src/components/core/CssBaseline/index.ts';
...
```

```bash
$ dts build -i src/index.ts
```

**Comment by prdxs** [comment]
What I want is different bundles for different entries, if that makes sense. And I thought providing many entries was the way to accomplish that.

**Comment by aladdin-add** [comment]
tsdx was designed to be an opinionated tool, seems not supported this way. But I'm open to add it in the fork.

**Comment by prdxs** [comment]
It's up to you. I think it might be useful for people writing a component library and don't want it all bundled in one file. I am not sure (correct me if I am wrong) but I think that if all the library comes in one file you cannot leverage tree-shaking.

I could give it a go too.

BTW, I love your fork TSDX idea is really good but they don't seem to be maintaining it anymore and this fork let me use the last version of ESLint, etc.

**Comment by aladdin-add** [comment]
as I can tell, most modern bundlers support esm tree-shaking, webpack/rollup/parcel/... so, it seems not a big deal to make a barrel index. But I agreed not every package has just one entry, e.g. eslint has two entries:  1) public api; 2) non-officially supported api. https://github.com/eslint/eslint/blob/e3cd1414489ceda460d593ac7e7b14f8ad45d4fc/package.json#L12-L13
it could be useful for these packages. PRs are welcome! 😄

**Comment by jy95** [comment]
If I correctly recall, there was one PR (never merged) in tsdx : https://github.com/jaredpalmer/tsdx/pull/367 
If @prdxs is willing to do a similar PR on this fork, why not ?
