### ISSUE TITLE
 It looks like you called `mount()` without a global document being loaded.

### ISSUE THREAD

**Issue by The-Code-Monkey** [weiran-zsd/dts-cli#87]
Ive just converted over from TSDX and the first issue im getting is when i run dts test i get this issue, have you come across this issue before.

**Comment by aladdin-add** [comment]
since jest v27, the default env has changed to node.js. to restore the old behaviour: `testEnvironment: 'node'`

**Comment by The-Code-Monkey** [comment]
ah ok cheers. I had no clue.
