### ISSUE TITLE
Alias issue on build

### ISSUE THREAD

**Issue by The-Code-Monkey** [weiran-zsd/dts-cli#88]
Sorry to keep bombarding with issues, but i seem to have got an issue as where the aliases that work normally don't seem to work when running the built files.

https://github.com/The-Code-Monkey/Components/runs/4141119026?check_suite_focus=true

**Comment by aladdin-add** [comment]
where did you define the aliases? IMHO, you should not define the aliases in your lib, as it will force your users to apply the same aliases.

**Comment by aladdin-add** [comment]
well, I see. https://github.com/The-Code-Monkey/Components/blob/3cc972a9478b9eb96a55b87c5a8e8b8ef529638c/jestAliasResolver.js#L15-L31

the error was from size-limit - the aliases were only known by jest, but not size-limit.

**Comment by The-Code-Monkey** [comment]
Do you know how to fix this as I thought it should just be picked up.
