### ISSUE TITLE
example version without installing dts-cli previously

### ISSUE THREAD

**Issue by aboveyunhai** [weiran-zsd/dts-cli#89]
If I don't call 
```
npm i dts-cli -D 
```
and directly call 
```
npx dts-cli create mylib
```
to install everything.
The `example` folder inside `mylib` is still using the old `parcel` one instead of `vite` one, which is problematic.

**Comment by aladdin-add** [comment]
have you installed global dts-cli? the new generated mylib's example should be using vite now.

**Comment by aboveyunhai** [comment]
> have you installed an older global dts-cli? the new generated mylib's example should be using vite now.

No, I actually check global npm first, there is neither `dts-cli` nor `tsdx`

**Comment by aladdin-add** [comment]
emm. that's weird. I was not able to repro in my end. :-( 

can you try `npx dts-cli@0.19.4 create mylib` to make sure it's using latest dts?

**Comment by aboveyunhai** [comment]
> emm. that's weird. I was not able to repro in my end. :-( 
> 
> can you try `npx dts-cli@0.19.4 create mylib` to make sure it's using latest dts?

With the lastest version, the example folder is correct/updated.

**Comment by aladdin-add** [comment]
closing as resolved! 🎉

**Comment by aboveyunhai** [comment]
@aladdin-add   By accident I found why I always installed the old version.
I check the cache folder via 
```
npm config get cache
```
under the folder `_npx` I actually find two stale cached versions of `dts-cli`. Removing them solves my problem.

I just leave it here in case someone faced the same problem on `windows 10`.
