### ISSUE TITLE
dts export

### ISSUE THREAD

**Issue by The-Code-Monkey** [weiran-zsd/dts-cli#96]
I wish there was a way we could run export like you can for create-react-app where it will unpack all the config files that it uses as well as install any packages it's using under the hood. So that we could update and tweak everything

**Comment by aladdin-add** [comment]
can you explain a little more why you want to "unpack"? IMO, the config is already [configurable](https://github.com/weiran-zsd/dts-cli#customization) - just adding your own `dts.config.js`, `.eslintrc.*`...

**Comment by The-Code-Monkey** [comment]
More the fact that I might want to update the packages manually rather than waiting for a new dts version.

**Comment by aladdin-add** [comment]
well, I see! a workaround is yarn resolutions: https://classic.yarnpkg.com/en/docs/selective-version-resolutions

**Comment by aladdin-add** [comment]
closing, as it seems `yarn resolutions/npm overrides` is the right way to go.
